### ISSUE TITLE
error compiling in doxygen_b bundle

### ISSUE THREAD

**Issue by raphaeldussin** [vovkos/axl#2]
```shell
doxyrest_b/axl/include/axl_lua/axl_lua_LuaState.h:141:21: error: ‘lua_len’ was not declared in this scope
   lua_len(m_h, index);
                     ^
```

similar errors for lua_rawlen, LUA_OK

compiling with cmake 3.7.2, Lua 5.1.0 in debian 4.9

**Comment by vovkos** [comment]
This particular error is easy to fix, but the AXL string template engine requires Lua 5.2 nevertheless.
 
A big issue with Lua 5.1 is that it's very strict with semicolons -- you can use only one and only after a Lua statement -- whereas the AXL string template engine inserts a semicolon after each %{ ... } script chunk extracted from a frame to eliminate unintended effects of code merging. It's possible to rewrite the string template without being dependent on semicolons, but it's not a "safe" one-liner fix...

Can you use Lua 5.2 on your machine? Or do you think it is critical to support Lua 5.1?

**Comment by raphaeldussin** [comment]
upgraded to Lua 5.2 and it works! I don't think it's critical to support older version, adding a note that AXL requires Lua >= 5.2 should be sufficient.
