### ISSUE TITLE
Implicit conversion of NULL constant to 'bool' in bool DynamicLib::getInfo

### ISSUE THREAD

**Issue by mingodad** [vovkos/axl#3]
In `src/axl_core/axl_sys_psx_DynamicLib.cpp:65:10:` warning: implicit conversion of NULL constant to 'bool'

```
#if (!_AXL_OS_DARWIN)

bool
DynamicLib::getInfo(
	int request,
	void* p
	)
{
	int result = ::dlinfo(m_h, request, p);
	if (!p)
	{
		err::setError(::dlerror());
		return NULL;  ///!!! should be 'false' instead of 'NULL'
	}

	return true;
}

#endif
```

**Comment by mingodad** [comment]
Also on `graco/src/Parser.cpp:362:10`: warning: implicit conversion of NULL constant to 'bool' [-Wnull-conversion]
                return NULL;
                ~~~~~~ ^~~~
                       false

**Comment by mingodad** [comment]
Also in `jancy/src/jnc_ct/jnc_ct_OperatorMgr/jnc_ct_OperatorMgr_Call.cpp:298:3`: warning: expression result unused [-Wunused-value]
                *baseArgumentIdx++;
                ^~~~~~~~~~~~~~~~~~
1 warning generated.

**Comment by mingodad** [comment]
Also in `jancy/src/jnc_ct/jnc_ct_OperatorMgr/jnc_ct_OperatorMgr_Closure.cpp:125:10`: warning: implicit conversion of NULL constant to 'bool' [-Wnull-conversion]
                return NULL;
                ~~~~~~ ^~~~
                       false
1 warning generated.

**Comment by mingodad** [comment]
Also in `jancy/src/jnc_ext/jnc_io_ssl/jnc_io_SslSocket.cpp:766:14`: warning: result of comparison of constant -1 with expression of type 'bool' is always false [-Wtautological-constant-out-of-range-compare]
                if (result == -1)
                    ~~~~~~ ^  ~~
1 warning generated.

**Comment by vovkos** [comment]
Thanks for the warning tips; I mostly develop on Linux (gcc) and Windows (msvc) so I don't normally see those Clang warnings. 

All fixed except for the last one. Re the last one -- I think you were using an older commit (the new ``jnc_io_SslSocket.cpp`` doesn't even have line 766). 

In the future, feel free to submit pull requests if you find anything like that.

**Comment by vovkos** [comment]
> Also you have not updated the jancy_b repository to get those fixes !

``jancy_b`` was automatically updated after both AppVeyor and TravisCI builds were completed successfully.  This June,
the free Travis CI org ceased to exist. As such, the CI pipelines need to be changed (most likely, to GitHub Actions, which I'm looking into now).

For the time being, I updated ``jancy_b`` manually. Feel free to do it by yourself next time (until the CI-based updates are up and running again)
